**Name:** Luan Minh Tran

**NetID:** lmt185

**RUID:** 197002611

In [2]:
# Rank of the matrix = maximum number of linearly independent column vectors
# Rank of the matrix = maximum number of linearly independent row vectors
from numpy.linalg import matrix_rank
from numpy.linalg import svd

In [5]:
mat = [[-1.32, -0.18, 2.13],
       [2.64, -4.68, 4.65],
       [1.47, -4.75, 6.80]]
# mat2 = [[1, 2, 3],
#         [2, 4, 6],
#         [3, 5, 8]]
print(mat)

[[-1.32, -0.18, 2.13], [2.64, -4.68, 4.65], [1.47, -4.75, 6.8]]


In [6]:
u, sigma, vh = svd(mat, full_matrices=True)
# u2, sigma2, vh2 = svd(mat2, full_matrices=True)
print(u)
print("\n")
print(sigma)
print("\n")
print(vh)
# print(u2)
# print("\n")
# print(sigma2)
# print("\n")
# print(vh2)

[[ 0.1288709  -0.81535465 -0.56443697]
 [ 0.63455281  0.50520086 -0.58490583]
 [ 0.76205973 -0.28278772  0.58249127]]


[11.01365384  2.54146561  0.09990768]


[[ 0.23837118 -0.60040816  0.76334083]
 [ 0.78470487 -0.34402767 -0.51563866]
 [ 0.57220403  0.72191066  0.38913692]]


In [ ]:
print("Rank of matrix is: ",  matrix_rank(mat))

Rank of matrix is:  3


# **Conclusion**
- Sigma "matrix" has the last value is 0.099.. => Not small enough to consider it as 0. So the Rank of given matrix is 3
- Rank = 3 so there are ***3 linearly independent columns***

# *Note:* 
- I test with matrix_rank() function and show the same result 
- I also create another matrix called ***mat2*** to test the svd method